### ISSUE TITLE
Cannot install library with Python 3.11

### ISSUE THREAD

**Issue by canassa** [hat-open/hat-util#1]
It's not possible to install the library with Python 3.11:

```
pip install hat-util
ERROR: Could not find a version that satisfies the requirement hat-util (from versions: none)
ERROR: No matching distribution found for hat-util
```

With Python 3.10 it works

**Comment by bozokopic** [comment]
just added python 3.11 support for hat-util, hat-json and hat-aio

other hat-* packages should also be compatible with 3.11, but we haven't tested yet. you can expect 3.11 support with new versions of these packages (hopefully in few days). if you need some of this packages running on 3.11, let me know and I will prioritize them.

best regards,
bozo
